import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import NavBarPage from "./NavBar/page";

const NunitoFont = Nunito({
  variable: "--font-Nunito-Font",
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`container mx-auto antialiased`}
    >
      <body className={`min-h-full flex flex-col ${NunitoFont.className} `}>
        <NavBarPage></NavBarPage>
        {children}
      </body>
    </html >
  );
}
